### ISSUE TITLE
Backlinks don't always work

### ISSUE THREAD

**Issue by honza** [jethrokuan/org-roam#116]
I checked the graph, and everything is connected the way I'd expect. However, someones the `org-roam` buffer has no backlinks where there should be some.

**Comment by alanz** [comment]
That could be prior to the fix landed at #107 for #102

**Comment by honza** [comment]
I'm running the latest `develop` 2d206134fde7158d95e49343d776dbedda1769c8

But I'll read through those issues just in case. Thanks

**Comment by alanz** [comment]
Well, they would have left junk in your db prior to the fix landing. It would create duplicate files for the same reference. So the backlink resolves to only one of them, and it seems the others have been missed.

**Comment by honza** [comment]
Does `org-roam` create some sort of database that's persisted to disk? I assume it was all in-memory.

**Comment by honza** [comment]
I cleared the cache, and restarted Emacs just to be sure but the issue persists.

**Comment by jethrokuan** [comment]
> Does org-roam create some sort of database that's persisted to disk? I assume it was all in-memory.

It's all in memory.

I'd need more info about what backlinks are missing in order to look into this

**Comment by brabalan** [comment]
I also have one backlink that does not work. This is what happened:
- I created a file using `org-roam-insert`
- noticing that the file name was not what I expected (recent changes on automatic naming), I deleted the file, changed my configuration, and did an `org-roam-insert` with the same title, that created a different file
- the backlink is not present

I can provide more debugging information, but I don't know how.

**Comment by jethrokuan** [comment]
> I deleted the file

The cache doesn't yet track file deletions and renames.It does however, rebuild backlinks for a given file on save.

> did an org-roam-insert with the same title, that created a different file
> the backlink is not present

I just tested this scenario where I:

1. created a file using `org-roam-insert`
2. deleted it
3. created another file using `org-roam-insert`
4. *saved the file*
5. visit new file

The backlinks are there as expected.

**Comment by honza** [comment]
Here is what I did:

* Delete all files on disk
* Quit Emacs
* Update org-roam to latest
* Start emacs
* Manually call the async cache building function
* `org-roam-find-file` to create a new named note
* Add a toplevel heading (i.e. `*`), and in that heading call `org-roam-insert` to reference a yet non-existent note
* Save the file
* Navigate to the reference in the heading, hit enter
* The linked reference opens in a new split.
* Switch to the new buffer
* Run `M-x org-roam`
* The popup buffer is empty.

**Comment by jethrokuan** [comment]
@honza can I also know:

1. Your emacs version
2. Your OS
3. Your value for org-roam-directory

I had someone tell me over mail org-roam didn't work over folders within a virtualbox, I just wanna confirm if anything else is abnormal with your setup.

**Comment by honza** [comment]
Emacs 26.3, Linux (Fedora), `org-roam-directory` is set to `~/Dropbox/org/` (files are correctly placed in that directory).

**Comment by honza** [comment]
I should note that the `org-roam` buffer is actually empty. It doesn't even have the header seen in your gifs.

**Comment by jethrokuan** [comment]
I see, did you add the org-roam-mode hook to Org-mode?

Can I have you check:
1. Is org-roam-mode activated in your org buffers
2. `C-h v post-command-hook` and see if there is a `org-roam--maybe-update-buffer` in the list

**Comment by honza** [comment]
That's exactly it. I can't believe I missed this. Thank you for your patience in helping me debug this. Everything works as expected now. Great stuff!

**Comment by meddulla** [comment]
Could you add more detail on how to "add the org-roam-mode hook to Org-mode"? I use spacemacs and simply followed the instructions in the website but although org-roam mostly works (inserting links, enabling/disabling org-roam-mode) I never see the backlinks buffer, it simply does not load. Listing buffers I don't see `org-roam-mode` there or `org-roam--maybe-update-buffer` in the `post-command-hook` variable.

**Comment by jethrokuan** [comment]
@meddulla to bring up the buffer, run `M-x org-roam`, which toggles the sidebar.

**Comment by jethrokuan** [comment]
Also, the install instructions above are old, you may need to replace them with new ones in the docs.

**Comment by meddulla** [comment]
I followed the instructions on the site/docs so those should be the last but don't have an option with just `org-roam`, that just brings up all org-roam options, [screenshot](https://www.dropbox.com/s/ggfshnu9rsiti30/Screenshot%202020-03-01%20at%2014.07.12.png?dl=0)

**Comment by jethrokuan** [comment]
That's really weird, what happens when you run `M-: (org-roam)`?

**Comment by meddulla** [comment]
`org-roam` is not listed under `M-`.. only have options like `applications`, `buffers`, `projects`, etc. (tbh don't know much about emacs itself, just use org-mode and get by without knowing much else)

**Comment by jethrokuan** [comment]
@meddulla `M-:` brings up a prompt for evaluating. Alternatively, you can do `M-x eval-expression`.

![image](https://user-images.githubusercontent.com/1667473/75674866-f9a46c00-5cc0-11ea-8c01-391ad62ea5b2.png)

Type `(org-roam)` and press enter.

**Comment by meddulla** [comment]
Thanks :) It opens up a new empty [buffer](https://www.dropbox.com/s/jmvyok7kzyonsdq/Screenshot%202020-03-02%20at%2012.06.32.png?dl=0)

**Comment by jethrokuan** [comment]
are you on the latest commit? can you show me your config? If you are on latest commit, can you evaluate the following expressions:

```
(org-roam--db-clear)
(org-roam-build-cache)
```

and show me what's printed at the after the `build-cache`

**Comment by meddulla** [comment]
Think that was because that page didn't have any backlinks but opening another file which should have and `eval'ing` again now shows the backlinks. So maybe it's being somehow loaded incorrectly? Here's my `packages.el` and `.spacemacs` https://gist.github.com/meddulla/0b59a19a65f689b5b69e455f9935da9b if it helps

**Comment by meddulla** [comment]
Sorry, hadn't seen your comment before posting mine. I was at commit `09a9273e2` and now pulled the latest changes. When running `org-roam-build-cache` I have [this](https://www.dropbox.com/s/gwlq5ja9syg433s/Screenshot%202020-03-02%20at%2012.24.57.png?dl=0)

**Comment by jethrokuan** [comment]
You ran `(org-roam--build-cache)`, not `(org-roam-build-cache)`.

**Comment by meddulla** [comment]
Sorry about that. Running that nothing much happens - it just shows `files 0, links 0, titles 0, refs 0, deleted 0`. Also noticed that when running `(org-roam)` sometimes the buffer is empty, sometimes not, both when viewing the same file. This particular file should always have backlinks.

**Comment by elliottw** [comment]
interesting, I've been having the same issue (macos spacemacs) and then realized that in the packages.el file in the instructions was:
`(org-roam-directory "/path/to/org-files/")`
I changed that to the root directory of my deft files, but now no links are working and all display like:`[[file:202001121736 recipes.org][202001121736 recipes]]`
but... the org-roam backlinking does seem to be working, only with that same broken formatting, from `*org-roam*`:
```
202001121736 recipes

* 2 Backlinks
** [[file:/Users/elliott/Dropbox/slipbox/202000000000 root.org][202000000000 root]]
[[file:202001121736%20recipes.org][recipes]]

** [[file:/Users/elliott/Dropbox/slipbox/2020-03-02.org][2020-03-02]]
[[file:202001121736 recipes.org][202001121736 recipes]]
```

**Comment by elliottw** [comment]
just changed the dir in packages.el and in .spacemacs away from my deft dir and rebuilt the cache thinking this might fix the problem, but still the same issues: org-roam sidebar works and shows links, but all links are in the broken format unrecognized by org-mode.

**Comment by elliottw** [comment]
seems like someone else is having this same issue [on emacs stackexchange](https://emacs.stackexchange.com/questions/55720/links-to-org-files-are-not-recognized-as-links-in-org-mode) and even sited org-roam as the issue. 

Seems like upgrading to `org` version `9.3.6-17-g389288-elpa` fixes the problem but for some reason i can't get spacemacs to install this version... maybe elpa is down.

**Comment by elliottw** [comment]
Tried on a different machine (ubuntu spacemacs same .spacemacs same .../packages.el) the upgrade of org fixed the problem. now I just need to figure out how to get org to update on my local macos/spacemacs.

**Comment by davidszpak** [comment]
> 1. Is org-roam-mode activated in your org buffers

Thank you. I had the exact same issue as the original poster. As described by you, putting this in my config (doom emacs) fixed the problem:
`(add-hook 'org-mode-hook #'org-roam-mode)`

**Comment by jethrokuan** [comment]
> As described by you, putting this in my config (doom emacs) fixed the problem:
(add-hook 'org-mode-hook #'org-roam-mode)

@davidszpak note that the mode is now global. So something like (add-hook 'after-init-hook 'org-roam-mode)` is preferred.

**Comment by tomekowal** [comment]
> Could you add more detail on how to "add the org-roam-mode hook to Org-mode"? I use spacemacs and simply followed the instructions in the website but although org-roam mostly works (inserting links, enabling/disabling org-roam-mode) I never see the backlinks buffer, it simply does not load. Listing buffers I don't see `org-roam-mode` there or `org-roam--maybe-update-buffer` in the `post-command-hook` variable.

@meddulla I recently had a similar issue and I think I solved it. I wasn't an org-mode user, so I didn't have the `org` layer in my spacemacs config. I discovered that org-mode works anyway but the hook for `org-roam` does not. Simply putting both `org` and `org-roam` in spacemacs configuration layers solved the issue.

**Comment by saurabhkukade** [comment]
I faced the similar issue and fixed this by installing and upgrading the following prerequisites.

`;; Package-Requires: ((emacs "26.1") (dash "2.13") (f "0.17.2") (org "9.4") (emacsql "3.0.0") (emacsql-sqlite "1.0.0") (magit-section "2.90.1"))
`
reference: [org-roam.el](https://github.com/org-roam/org-roam/blob/master/org-roam.el)

**Comment by nyc-tinker** [comment]
When this occurred in my case (on emacs 30), in `org-roam-utils.el`  located [here](https://github.com/org-roam/org-roam/blob/f9228ce31969cab9ca46ad4890e82e2ea7de3738/org-roam-utils.el#LL233C20-L233C20) was `(org-font-lock-ensure)`.  Seems like I had an old version of the `org-roam-utils.el` file.

Editing that snippet to `(font-lock-ensure)` from `(org-font-lock-ensure)` fixed the issue for me

**Comment by jhncondix** [comment]
I am on Emacs 28.1 with the latest org and org roam. Org roam backlinks rarely appear when I link to a node, although sometimes they do. There is no rhyme or reason. Most of the time, unfortunately, I will have to close and reopen emacs. Then they are always there. So the database often seems to require restarting emacs in order to show updated links.
